#!/usr/bin/env bash
# displays Best School 10 times, but for the 4th 8th iteration,
# display luck

i=0

while ((i<10))
do
	if ((i == 3))
	then
		echo "bad luck"
	elif ((i == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
