#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user.
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/listen [::]:80 default_server;/listen [::]:8080 default_server;/" /etc/nginx/sites-enabled/default
service nginx restart
sudo -u nginx service nginx start
